# Load Swapr/Algebra ABIs

ALGEBRA_POOL_ABI = [
   {
      "inputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"constructor"
   },
   {
      "anonymous":False,
      "inputs":[
         {
            "indexed":True,
            "internalType":"address",
            "name":"owner",
            "type":"address"
         },
         {
            "indexed":True,
            "internalType":"int24",
            "name":"bottomTick",
            "type":"int24"
         },
         {
            "indexed":True,
            "internalType":"int24",
            "name":"topTick",
            "type":"int24"
         },
         {
            "indexed":False,
            "internalType":"uint128",
            "name":"liquidityAmount",
            "type":"uint128"
         },
         {
            "indexed":False,
            "internalType":"uint256",
            "name":"amount0",
            "type":"uint256"
         },
         {
            "indexed":False,
            "internalType":"uint256",
            "name":"amount1",
            "type":"uint256"
         }
      ],
      "name":"Burn",
      "type":"event"
   },
   {
      "anonymous":False,
      "inputs":[
         {
            "indexed":True,
            "internalType":"address",
            "name":"owner",
            "type":"address"
         },
         {
            "indexed":False,
            "internalType":"address",
            "name":"recipient",
            "type":"address"
         },
         {
            "indexed":True,
            "internalType":"int24",
            "name":"bottomTick",
            "type":"int24"
         },
         {
            "indexed":True,
            "internalType":"int24",
            "name":"topTick",
            "type":"int24"
         },
         {
            "indexed":False,
            "internalType":"uint128",
            "name":"amount0",
            "type":"uint128"
         },
         {
            "indexed":False,
            "internalType":"uint128",
            "name":"amount1",
            "type":"uint128"
         }
      ],
      "name":"Collect",
      "type":"event"
   },
   {
      "anonymous":False,
      "inputs":[
         {
            "indexed":False,
            "internalType":"uint8",
            "name":"communityFee0New",
            "type":"uint8"
         },
         {
            "indexed":False,
            "internalType":"uint8",
            "name":"communityFee1New",
            "type":"uint8"
         }
      ],
      "name":"CommunityFee",
      "type":"event"
   },
   {
      "anonymous":False,
      "inputs":[
         {
            "indexed":False,
            "internalType":"uint16",
            "name":"fee",
            "type":"uint16"
         }
      ],
      "name":"Fee",
      "type":"event"
   },
   {
      "anonymous":False,
      "inputs":[
         {
            "indexed":True,
            "internalType":"address",
            "name":"sender",
            "type":"address"
         },
         {
            "indexed":True,
            "internalType":"address",
            "name":"recipient",
            "type":"address"
         },
         {
            "indexed":False,
            "internalType":"uint256",
            "name":"amount0",
            "type":"uint256"
         },
         {
            "indexed":False,
            "internalType":"uint256",
            "name":"amount1",
            "type":"uint256"
         },
         {
            "indexed":False,
            "internalType":"uint256",
            "name":"paid0",
            "type":"uint256"
         },
         {
            "indexed":False,
            "internalType":"uint256",
            "name":"paid1",
            "type":"uint256"
         }
      ],
      "name":"Flash",
      "type":"event"
   },
   {
      "anonymous":False,
      "inputs":[
         {
            "indexed":True,
            "internalType":"address",
            "name":"virtualPoolAddress",
            "type":"address"
         }
      ],
      "name":"Incentive",
      "type":"event"
   },
   {
      "anonymous":False,
      "inputs":[
         {
            "indexed":False,
            "internalType":"uint160",
            "name":"price",
            "type":"uint160"
         },
         {
            "indexed":False,
            "internalType":"int24",
            "name":"tick",
            "type":"int24"
         }
      ],
      "name":"Initialize",
      "type":"event"
   },
   {
      "anonymous":False,
      "inputs":[
         {
            "indexed":False,
            "internalType":"uint32",
            "name":"liquidityCooldown",
            "type":"uint32"
         }
      ],
      "name":"LiquidityCooldown",
      "type":"event"
   },
   {
      "anonymous":False,
      "inputs":[
         {
            "indexed":False,
            "internalType":"address",
            "name":"sender",
            "type":"address"
         },
         {
            "indexed":True,
            "internalType":"address",
            "name":"owner",
            "type":"address"
         },
         {
            "indexed":True,
            "internalType":"int24",
            "name":"bottomTick",
            "type":"int24"
         },
         {
            "indexed":True,
            "internalType":"int24",
            "name":"topTick",
            "type":"int24"
         },
         {
            "indexed":False,
            "internalType":"uint128",
            "name":"liquidityAmount",
            "type":"uint128"
         },
         {
            "indexed":False,
            "internalType":"uint256",
            "name":"amount0",
            "type":"uint256"
         },
         {
            "indexed":False,
            "internalType":"uint256",
            "name":"amount1",
            "type":"uint256"
         }
      ],
      "name":"Mint",
      "type":"event"
   },
   {
      "anonymous":False,
      "inputs":[
         {
            "indexed":True,
            "internalType":"address",
            "name":"sender",
            "type":"address"
         },
         {
            "indexed":True,
            "internalType":"address",
            "name":"recipient",
            "type":"address"
         },
         {
            "indexed":False,
            "internalType":"int256",
            "name":"amount0",
            "type":"int256"
         },
         {
            "indexed":False,
            "internalType":"int256",
            "name":"amount1",
            "type":"int256"
         },
         {
            "indexed":False,
            "internalType":"uint160",
            "name":"price",
            "type":"uint160"
         },
         {
            "indexed":False,
            "internalType":"uint128",
            "name":"liquidity",
            "type":"uint128"
         },
         {
            "indexed":False,
            "internalType":"int24",
            "name":"tick",
            "type":"int24"
         }
      ],
      "name":"Swap",
      "type":"event"
   },
   {
      "anonymous":False,
      "inputs":[
         {
            "indexed":False,
            "internalType":"int24",
            "name":"newTickSpacing",
            "type":"int24"
         }
      ],
      "name":"TickSpacing",
      "type":"event"
   },
   {
      "inputs":[
         
      ],
      "name":"activeIncentive",
      "outputs":[
         {
            "internalType":"address",
            "name":"",
            "type":"address"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"int24",
            "name":"bottomTick",
            "type":"int24"
         },
         {
            "internalType":"int24",
            "name":"topTick",
            "type":"int24"
         },
         {
            "internalType":"uint128",
            "name":"amount",
            "type":"uint128"
         }
      ],
      "name":"burn",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"amount0",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"amount1",
            "type":"uint256"
         }
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"recipient",
            "type":"address"
         },
         {
            "internalType":"int24",
            "name":"bottomTick",
            "type":"int24"
         },
         {
            "internalType":"int24",
            "name":"topTick",
            "type":"int24"
         },
         {
            "internalType":"uint128",
            "name":"amount0Requested",
            "type":"uint128"
         },
         {
            "internalType":"uint128",
            "name":"amount1Requested",
            "type":"uint128"
         }
      ],
      "name":"collect",
      "outputs":[
         {
            "internalType":"uint128",
            "name":"amount0",
            "type":"uint128"
         },
         {
            "internalType":"uint128",
            "name":"amount1",
            "type":"uint128"
         }
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"dataStorageOperator",
      "outputs":[
         {
            "internalType":"address",
            "name":"",
            "type":"address"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"factory",
      "outputs":[
         {
            "internalType":"address",
            "name":"",
            "type":"address"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"recipient",
            "type":"address"
         },
         {
            "internalType":"uint256",
            "name":"amount0",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"amount1",
            "type":"uint256"
         },
         {
            "internalType":"bytes",
            "name":"data",
            "type":"bytes"
         }
      ],
      "name":"flash",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"int24",
            "name":"bottomTick",
            "type":"int24"
         },
         {
            "internalType":"int24",
            "name":"topTick",
            "type":"int24"
         }
      ],
      "name":"getInnerCumulatives",
      "outputs":[
         {
            "internalType":"int56",
            "name":"innerTickCumulative",
            "type":"int56"
         },
         {
            "internalType":"uint160",
            "name":"innerSecondsSpentPerLiquidity",
            "type":"uint160"
         },
         {
            "internalType":"uint32",
            "name":"innerSecondsSpent",
            "type":"uint32"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint32[]",
            "name":"secondsAgos",
            "type":"uint32[]"
         }
      ],
      "name":"getTimepoints",
      "outputs":[
         {
            "internalType":"int56[]",
            "name":"tickCumulatives",
            "type":"int56[]"
         },
         {
            "internalType":"uint160[]",
            "name":"secondsPerLiquidityCumulatives",
            "type":"uint160[]"
         },
         {
            "internalType":"uint112[]",
            "name":"volatilityCumulatives",
            "type":"uint112[]"
         },
         {
            "internalType":"uint256[]",
            "name":"volumePerAvgLiquiditys",
            "type":"uint256[]"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"globalState",
      "outputs":[
         {
            "internalType":"uint160",
            "name":"price",
            "type":"uint160"
         },
         {
            "internalType":"int24",
            "name":"tick",
            "type":"int24"
         },
         {
            "internalType":"uint16",
            "name":"fee",
            "type":"uint16"
         },
         {
            "internalType":"uint16",
            "name":"timepointIndex",
            "type":"uint16"
         },
         {
            "internalType":"uint8",
            "name":"communityFeeToken0",
            "type":"uint8"
         },
         {
            "internalType":"uint8",
            "name":"communityFeeToken1",
            "type":"uint8"
         },
         {
            "internalType":"bool",
            "name":"unlocked",
            "type":"bool"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint160",
            "name":"initialPrice",
            "type":"uint160"
         }
      ],
      "name":"initialize",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"liquidity",
      "outputs":[
         {
            "internalType":"uint128",
            "name":"",
            "type":"uint128"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"liquidityCooldown",
      "outputs":[
         {
            "internalType":"uint32",
            "name":"",
            "type":"uint32"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"maxLiquidityPerTick",
      "outputs":[
         {
            "internalType":"uint128",
            "name":"",
            "type":"uint128"
         }
      ],
      "stateMutability":"pure",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"sender",
            "type":"address"
         },
         {
            "internalType":"address",
            "name":"recipient",
            "type":"address"
         },
         {
            "internalType":"int24",
            "name":"bottomTick",
            "type":"int24"
         },
         {
            "internalType":"int24",
            "name":"topTick",
            "type":"int24"
         },
         {
            "internalType":"uint128",
            "name":"liquidityDesired",
            "type":"uint128"
         },
         {
            "internalType":"bytes",
            "name":"data",
            "type":"bytes"
         }
      ],
      "name":"mint",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"amount0",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"amount1",
            "type":"uint256"
         },
         {
            "internalType":"uint128",
            "name":"liquidityActual",
            "type":"uint128"
         }
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"bytes32",
            "name":"",
            "type":"bytes32"
         }
      ],
      "name":"positions",
      "outputs":[
         {
            "internalType":"uint128",
            "name":"liquidity",
            "type":"uint128"
         },
         {
            "internalType":"uint32",
            "name":"lastLiquidityAddTimestamp",
            "type":"uint32"
         },
         {
            "internalType":"uint256",
            "name":"innerFeeGrowth0Token",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"innerFeeGrowth1Token",
            "type":"uint256"
         },
         {
            "internalType":"uint128",
            "name":"fees0",
            "type":"uint128"
         },
         {
            "internalType":"uint128",
            "name":"fees1",
            "type":"uint128"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint8",
            "name":"communityFee0",
            "type":"uint8"
         },
         {
            "internalType":"uint8",
            "name":"communityFee1",
            "type":"uint8"
         }
      ],
      "name":"setCommunityFee",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"virtualPoolAddress",
            "type":"address"
         }
      ],
      "name":"setIncentive",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint32",
            "name":"newLiquidityCooldown",
            "type":"uint32"
         }
      ],
      "name":"setLiquidityCooldown",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"int24",
            "name":"newTickSpacing",
            "type":"int24"
         }
      ],
      "name":"setTickSpacing",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"recipient",
            "type":"address"
         },
         {
            "internalType":"bool",
            "name":"zeroToOne",
            "type":"bool"
         },
         {
            "internalType":"int256",
            "name":"amountRequired",
            "type":"int256"
         },
         {
            "internalType":"uint160",
            "name":"limitSqrtPrice",
            "type":"uint160"
         },
         {
            "internalType":"bytes",
            "name":"data",
            "type":"bytes"
         }
      ],
      "name":"swap",
      "outputs":[
         {
            "internalType":"int256",
            "name":"amount0",
            "type":"int256"
         },
         {
            "internalType":"int256",
            "name":"amount1",
            "type":"int256"
         }
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"sender",
            "type":"address"
         },
         {
            "internalType":"address",
            "name":"recipient",
            "type":"address"
         },
         {
            "internalType":"bool",
            "name":"zeroToOne",
            "type":"bool"
         },
         {
            "internalType":"int256",
            "name":"amountRequired",
            "type":"int256"
         },
         {
            "internalType":"uint160",
            "name":"limitSqrtPrice",
            "type":"uint160"
         },
         {
            "internalType":"bytes",
            "name":"data",
            "type":"bytes"
         }
      ],
      "name":"swapSupportingFeeOnInputTokens",
      "outputs":[
         {
            "internalType":"int256",
            "name":"amount0",
            "type":"int256"
         },
         {
            "internalType":"int256",
            "name":"amount1",
            "type":"int256"
         }
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"tickSpacing",
      "outputs":[
         {
            "internalType":"int24",
            "name":"",
            "type":"int24"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"int16",
            "name":"",
            "type":"int16"
         }
      ],
      "name":"tickTable",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"int24",
            "name":"",
            "type":"int24"
         }
      ],
      "name":"ticks",
      "outputs":[
         {
            "internalType":"uint128",
            "name":"liquidityTotal",
            "type":"uint128"
         },
         {
            "internalType":"int128",
            "name":"liquidityDelta",
            "type":"int128"
         },
         {
            "internalType":"uint256",
            "name":"outerFeeGrowth0Token",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"outerFeeGrowth1Token",
            "type":"uint256"
         },
         {
            "internalType":"int56",
            "name":"outerTickCumulative",
            "type":"int56"
         },
         {
            "internalType":"uint160",
            "name":"outerSecondsPerLiquidity",
            "type":"uint160"
         },
         {
            "internalType":"uint32",
            "name":"outerSecondsSpent",
            "type":"uint32"
         },
         {
            "internalType":"bool",
            "name":"initialized",
            "type":"bool"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"index",
            "type":"uint256"
         }
      ],
      "name":"timepoints",
      "outputs":[
         {
            "internalType":"bool",
            "name":"initialized",
            "type":"bool"
         },
         {
            "internalType":"uint32",
            "name":"blockTimestamp",
            "type":"uint32"
         },
         {
            "internalType":"int56",
            "name":"tickCumulative",
            "type":"int56"
         },
         {
            "internalType":"uint160",
            "name":"secondsPerLiquidityCumulative",
            "type":"uint160"
         },
         {
            "internalType":"uint88",
            "name":"volatilityCumulative",
            "type":"uint88"
         },
         {
            "internalType":"int24",
            "name":"averageTick",
            "type":"int24"
         },
         {
            "internalType":"uint144",
            "name":"volumePerLiquidityCumulative",
            "type":"uint144"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"token0",
      "outputs":[
         {
            "internalType":"address",
            "name":"",
            "type":"address"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"token1",
      "outputs":[
         {
            "internalType":"address",
            "name":"",
            "type":"address"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"totalFeeGrowth0Token",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"totalFeeGrowth1Token",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   }
]

SWAPR_ROUTER_ABI = [
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"_factory",
             "type":"address"
          },
          {
             "internalType":"address",
             "name":"_WNativeToken",
             "type":"address"
          },
          {
             "internalType":"address",
             "name":"_poolDeployer",
             "type":"address"
          }
       ],
       "stateMutability":"nonpayable",
       "type":"constructor"
    },
    {
       "inputs":[
          
       ],
       "name":"WNativeToken",
       "outputs":[
          {
             "internalType":"address",
             "name":"",
             "type":"address"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"int256",
             "name":"amount0Delta",
             "type":"int256"
          },
          {
             "internalType":"int256",
             "name":"amount1Delta",
             "type":"int256"
          },
          {
             "internalType":"bytes",
             "name":"_data",
             "type":"bytes"
          }
       ],
       "name":"algebraSwapCallback",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "components":[
                {
                   "internalType":"bytes",
                   "name":"path",
                   "type":"bytes"
                },
                {
                   "internalType":"address",
                   "name":"recipient",
                   "type":"address"
                },
                {
                   "internalType":"uint256",
                   "name":"deadline",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"amountIn",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"amountOutMinimum",
                   "type":"uint256"
                }
             ],
             "internalType":"struct ISwapRouter.ExactInputParams",
             "name":"params",
             "type":"tuple"
          }
       ],
       "name":"exactInput",
       "outputs":[
          {
             "internalType":"uint256",
             "name":"amountOut",
             "type":"uint256"
          }
       ],
       "stateMutability":"payable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "components":[
                {
                   "internalType":"address",
                   "name":"tokenIn",
                   "type":"address"
                },
                {
                   "internalType":"address",
                   "name":"tokenOut",
                   "type":"address"
                },
                {
                   "internalType":"address",
                   "name":"recipient",
                   "type":"address"
                },
                {
                   "internalType":"uint256",
                   "name":"deadline",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"amountIn",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"amountOutMinimum",
                   "type":"uint256"
                },
                {
                   "internalType":"uint160",
                   "name":"limitSqrtPrice",
                   "type":"uint160"
                }
             ],
             "internalType":"struct ISwapRouter.ExactInputSingleParams",
             "name":"params",
             "type":"tuple"
          }
       ],
       "name":"exactInputSingle",
       "outputs":[
          {
             "internalType":"uint256",
             "name":"amountOut",
             "type":"uint256"
          }
       ],
       "stateMutability":"payable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "components":[
                {
                   "internalType":"address",
                   "name":"tokenIn",
                   "type":"address"
                },
                {
                   "internalType":"address",
                   "name":"tokenOut",
                   "type":"address"
                },
                {
                   "internalType":"address",
                   "name":"recipient",
                   "type":"address"
                },
                {
                   "internalType":"uint256",
                   "name":"deadline",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"amountIn",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"amountOutMinimum",
                   "type":"uint256"
                },
                {
                   "internalType":"uint160",
                   "name":"limitSqrtPrice",
                   "type":"uint160"
                }
             ],
             "internalType":"struct ISwapRouter.ExactInputSingleParams",
             "name":"params",
             "type":"tuple"
          }
       ],
       "name":"exactInputSingleSupportingFeeOnTransferTokens",
       "outputs":[
          {
             "internalType":"uint256",
             "name":"amountOut",
             "type":"uint256"
          }
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "components":[
                {
                   "internalType":"bytes",
                   "name":"path",
                   "type":"bytes"
                },
                {
                   "internalType":"address",
                   "name":"recipient",
                   "type":"address"
                },
                {
                   "internalType":"uint256",
                   "name":"deadline",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"amountOut",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"amountInMaximum",
                   "type":"uint256"
                }
             ],
             "internalType":"struct ISwapRouter.ExactOutputParams",
             "name":"params",
             "type":"tuple"
          }
       ],
       "name":"exactOutput",
       "outputs":[
          {
             "internalType":"uint256",
             "name":"amountIn",
             "type":"uint256"
          }
       ],
       "stateMutability":"payable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "components":[
                {
                   "internalType":"address",
                   "name":"tokenIn",
                   "type":"address"
                },
                {
                   "internalType":"address",
                   "name":"tokenOut",
                   "type":"address"
                },
                {
                   "internalType":"uint24",
                   "name":"fee",
                   "type":"uint24"
                },
                {
                   "internalType":"address",
                   "name":"recipient",
                   "type":"address"
                },
                {
                   "internalType":"uint256",
                   "name":"deadline",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"amountOut",
                   "type":"uint256"
                },
                {
                   "internalType":"uint256",
                   "name":"amountInMaximum",
                   "type":"uint256"
                },
                {
                   "internalType":"uint160",
                   "name":"limitSqrtPrice",
                   "type":"uint160"
                }
             ],
             "internalType":"struct ISwapRouter.ExactOutputSingleParams",
             "name":"params",
             "type":"tuple"
          }
       ],
       "name":"exactOutputSingle",
       "outputs":[
          {
             "internalType":"uint256",
             "name":"amountIn",
             "type":"uint256"
          }
       ],
       "stateMutability":"payable",
       "type":"function"
    },
    {
       "inputs":[
          
       ],
       "name":"factory",
       "outputs":[
          {
             "internalType":"address",
             "name":"",
             "type":"address"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"bytes[]",
             "name":"data",
             "type":"bytes[]"
          }
       ],
       "name":"multicall",
       "outputs":[
          {
             "internalType":"bytes[]",
             "name":"results",
             "type":"bytes[]"
          }
       ],
       "stateMutability":"payable",
       "type":"function"
    },
    {
       "inputs":[
          
       ],
       "name":"poolDeployer",
       "outputs":[
          {
             "internalType":"address",
             "name":"",
             "type":"address"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          
       ],
       "name":"refundNativeToken",
       "outputs":[
          
       ],
       "stateMutability":"payable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"token",
             "type":"address"
          },
          {
             "internalType":"uint256",
             "name":"value",
             "type":"uint256"
          },
          {
             "internalType":"uint256",
             "name":"deadline",
             "type":"uint256"
          },
          {
             "internalType":"uint8",
             "name":"v",
             "type":"uint8"
          },
          {
             "internalType":"bytes32",
             "name":"r",
             "type":"bytes32"
          },
          {
             "internalType":"bytes32",
             "name":"s",
             "type":"bytes32"
          }
       ],
       "name":"selfPermit",
       "outputs":[
          
       ],
       "stateMutability":"payable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"token",
             "type":"address"
          },
          {
             "internalType":"uint256",
             "name":"nonce",
             "type":"uint256"
          },
          {
             "internalType":"uint256",
             "name":"expiry",
             "type":"uint256"
          },
          {
             "internalType":"uint8",
             "name":"v",
             "type":"uint8"
          },
          {
             "internalType":"bytes32",
             "name":"r",
             "type":"bytes32"
          },
          {
             "internalType":"bytes32",
             "name":"s",
             "type":"bytes32"
          }
       ],
       "name":"selfPermitAllowed",
       "outputs":[
          
       ],
       "stateMutability":"payable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"token",
             "type":"address"
          },
          {
             "internalType":"uint256",
             "name":"nonce",
             "type":"uint256"
          },
          {
             "internalType":"uint256",
             "name":"expiry",
             "type":"uint256"
          },
          {
             "internalType":"uint8",
             "name":"v",
             "type":"uint8"
          },
          {
             "internalType":"bytes32",
             "name":"r",
             "type":"bytes32"
          },
          {
             "internalType":"bytes32",
             "name":"s",
             "type":"bytes32"
          }
       ],
       "name":"selfPermitAllowedIfNecessary",
       "outputs":[
          
       ],
       "stateMutability":"payable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"token",
             "type":"address"
          },
          {
             "internalType":"uint256",
             "name":"value",
             "type":"uint256"
          },
          {
             "internalType":"uint256",
             "name":"deadline",
             "type":"uint256"
          },
          {
             "internalType":"uint8",
             "name":"v",
             "type":"uint8"
          },
          {
             "internalType":"bytes32",
             "name":"r",
             "type":"bytes32"
          },
          {
             "internalType":"bytes32",
             "name":"s",
             "type":"bytes32"
          }
       ],
       "name":"selfPermitIfNecessary",
       "outputs":[
          
       ],
       "stateMutability":"payable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"token",
             "type":"address"
          },
          {
             "internalType":"uint256",
             "name":"amountMinimum",
             "type":"uint256"
          },
          {
             "internalType":"address",
             "name":"recipient",
             "type":"address"
          }
       ],
       "name":"sweepToken",
       "outputs":[
          
       ],
       "stateMutability":"payable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"token",
             "type":"address"
          },
          {
             "internalType":"uint256",
             "name":"amountMinimum",
             "type":"uint256"
          },
          {
             "internalType":"address",
             "name":"recipient",
             "type":"address"
          },
          {
             "internalType":"uint256",
             "name":"feeBips",
             "type":"uint256"
          },
          {
             "internalType":"address",
             "name":"feeRecipient",
             "type":"address"
          }
       ],
       "name":"sweepTokenWithFee",
       "outputs":[
          
       ],
       "stateMutability":"payable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"uint256",
             "name":"amountMinimum",
             "type":"uint256"
          },
          {
             "internalType":"address",
             "name":"recipient",
             "type":"address"
          }
       ],
       "name":"unwrapWNativeToken",
       "outputs":[
          
       ],
       "stateMutability":"payable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"uint256",
             "name":"amountMinimum",
             "type":"uint256"
          },
          {
             "internalType":"address",
             "name":"recipient",
             "type":"address"
          },
          {
             "internalType":"uint256",
             "name":"feeBips",
             "type":"uint256"
          },
          {
             "internalType":"address",
             "name":"feeRecipient",
             "type":"address"
          }
       ],
       "name":"unwrapWNativeTokenWithFee",
       "outputs":[
          
       ],
       "stateMutability":"payable",
       "type":"function"
    },
    {
       "stateMutability":"payable",
       "type":"receive"
    }
 ]

__all__ = [
    'SWAPR_ROUTER_ABI',
    'ALGEBRA_POOL_ABI'
]